### ISSUE TITLE
option aliases

### ISSUE THREAD

**Issue by tehpsalmist** [ZengineHQ/mayan#24]
I personally like to type as few characters as possible, if I have to type at all, so cutting down `mayan publish --yes` to `mayan p -y` would be great. Also, `--frontend` to `-f`, etc. I think it's fairly simple with yargs, but I've never done it. Also interested to know if anyone else has strong opinions on this before I look into it.

**Comment by evert0n** [comment]
I agree with the sentiment but I personally wouldn't introduce that concept in here for a few reasons

- you will run out of chars to represent it at some point
- it's a bit crypt for both new and advanced users
- if we ever improve testing it will double effort to make sure it work both ways
- if you are really typing it every time probably you need a better shell or use the command history otherwise the time you are saving typing the full args don't seem a big gain

Last I think there a couple of other stuff (see Issues list) that could be a better use of time

**Comment by tehpsalmist** [comment]
I'm just trying to save the world one keystroke at a time, bro.

**Comment by alexweber** [comment]
@tehpsalmist @evert0n For what it's worth I think it would be nice to add these as power-user aliases, we can even leave them out of the help text displayed on screen but I agree with the sentiment that it can be annoying to type these long things every time...

Also, the original maya allowed passing `-y` to skip confirmations but when I was developing on mayan I was unable to get `-y` to work so I added `--yes` as a workaround because I was under time constraints.  

To be honest, `--yes` is totally stupid and unorthodox lol I hate it but to Everton's point it's hard to justify time spent on this with other possibly more important things to do.
